CREATE TABLE investors (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    risk_profile    VARCHAR(20)  NOT NULL,
    status          VARCHAR(1)   NOT NULL,
    created_date    TIMESTAMP    NOT NULL,
    updated_date    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_investors_email UNIQUE (email)
);

CREATE TABLE portfolios (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investor_id     BIGINT       NOT NULL REFERENCES investors (id),
    portfolio_name  VARCHAR(255) NOT NULL,
    status          VARCHAR(1)   NOT NULL,
    created_date    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_portfolios_investor_name UNIQUE (investor_id, portfolio_name)
);

CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id    BIGINT         NOT NULL REFERENCES portfolios (id),
    symbol          VARCHAR(100)   NOT NULL,
    quantity        BIGINT         NOT NULL,
    order_type      VARCHAR(10)    NOT NULL,
    price           NUMERIC(19, 4) NOT NULL,
    order_status    VARCHAR(20)    NOT NULL,
    status          VARCHAR(1)     NOT NULL,
    created_date    TIMESTAMP      NOT NULL,
    updated_date    TIMESTAMP      NOT NULL
);

CREATE INDEX idx_orders_portfolio_id ON orders (portfolio_id);

CREATE TABLE holdings (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id    BIGINT         NOT NULL REFERENCES portfolios (id),
    symbol          VARCHAR(100)   NOT NULL,
    quantity        BIGINT         NOT NULL,
    average_price   NUMERIC(19, 4) NOT NULL,
    version         INTEGER        NOT NULL DEFAULT 0,
    status          VARCHAR(1)     NOT NULL,
    created_date    TIMESTAMP      NOT NULL,
    updated_date    TIMESTAMP      NOT NULL
);

CREATE INDEX idx_holdings_portfolio_id_symbol_status ON holdings (portfolio_id, symbol, status);
