spring:
  application:
    name: PortfolioService

  datasource:
    url: jdbc:postgresql://localhost:5432/wealth_plus_db
    username: user
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer