CREATE TABLE notification_history (
                                      id                      BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      alert_configuration_id  BIGINT         NOT NULL,
                                      portfolio_id            BIGINT,
                                      symbol                  VARCHAR(100),
                                      alert_type              VARCHAR(20)    NOT NULL,
                                      message                 VARCHAR(500)   NOT NULL,
                                      status                  VARCHAR(1)     NOT NULL,
                                      triggered_value         NUMERIC(19, 4) NOT NULL,
                                      triggered_at            TIMESTAMP      NOT NULL,
                                      received_at             TIMESTAMP      NOT NULL
);

CREATE INDEX idx_notification_history_portfolio_id ON notification_history (portfolio_id);
CREATE INDEX idx_notification_history_alert_configuration_id ON notification_history (alert_configuration_id);