CREATE TABLE portfolio_holdings_snapshots (
    id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id        BIGINT         NOT NULL,
    symbol              VARCHAR(100)   NOT NULL,
    quantity            BIGINT         NOT NULL,
    average_price       NUMERIC(19, 4) NOT NULL,
    latest_market_price NUMERIC(19, 4) NOT NULL,
    status              VARCHAR(1)     NOT NULL,
    CONSTRAINT uq_holdings_snapshot_portfolio_symbol UNIQUE (portfolio_id, symbol)
);

CREATE INDEX idx_holdings_snapshot_symbol_status ON portfolio_holdings_snapshots (symbol, status);
CREATE INDEX idx_holdings_snapshot_portfolio_status ON portfolio_holdings_snapshots (portfolio_id, status);

CREATE TABLE portfolio_metrics (
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id     BIGINT         NOT NULL,
    current_value    NUMERIC(19, 4) NOT NULL,
    invested_amount  NUMERIC(19, 4) NOT NULL,
    pnl              NUMERIC(19, 4) NOT NULL,
    xirr             NUMERIC(19, 4) NOT NULL,
    CONSTRAINT uq_portfolio_metrics_portfolio_id UNIQUE (portfolio_id)
);
