CREATE TABLE alert_portfolio_holdings (
    id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id        BIGINT         NOT NULL,
    symbol              VARCHAR(100)   NOT NULL,
    quantity            BIGINT         NOT NULL,
    average_price       NUMERIC(19, 4) NOT NULL,
    latest_market_price NUMERIC(19, 4) NOT NULL,
    status              VARCHAR(1)     NOT NULL,
    created_date        TIMESTAMP      NOT NULL,
    CONSTRAINT uq_alert_holdings_portfolio_symbol UNIQUE (portfolio_id, symbol)
);

CREATE INDEX idx_alert_holdings_symbol_status ON alert_portfolio_holdings (symbol, status);
CREATE INDEX idx_alert_holdings_portfolio_status ON alert_portfolio_holdings (portfolio_id, status);

CREATE TABLE alert_configuration (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id    BIGINT,
    symbol          VARCHAR(100),
    alert_type      VARCHAR(20)    NOT NULL,
    condition       VARCHAR(20)    NOT NULL,
    threshold_value NUMERIC(19, 4) NOT NULL,
    status          VARCHAR(1)     NOT NULL,
    created_date    TIMESTAMP      NOT NULL
);

CREATE INDEX idx_alert_configuration_symbol_type_status ON alert_configuration (symbol, alert_type, status);
CREATE INDEX idx_alert_configuration_portfolio_type_status ON alert_configuration (portfolio_id, alert_type, status);

CREATE TABLE alert_history (
    id                      BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_configuration_id  BIGINT         NOT NULL REFERENCES alert_configuration (id),
    portfolio_id            BIGINT,
    symbol                  VARCHAR(100),
    alert_type              VARCHAR(20)    NOT NULL,
    message                 VARCHAR(500)   NOT NULL,
    triggered_value         NUMERIC(19, 4) NOT NULL,
    triggered_at            TIMESTAMP      NOT NULL
);

CREATE INDEX idx_alert_history_configuration_id ON alert_history (alert_configuration_id);
