CREATE TABLE robo_portfolio_holding (
                                          id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          portfolio_id        BIGINT         NOT NULL,
                                          symbol              VARCHAR(100)   NOT NULL,
                                          quantity            BIGINT         NOT NULL,
                                          average_price       NUMERIC(19, 4) NOT NULL,
                                          latest_market_price NUMERIC(19, 4) NOT NULL,
                                          status              VARCHAR(1)     NOT NULL,
                                          created_date        TIMESTAMP      NOT NULL,
                                          CONSTRAINT uq_robo_portfolio_holdings_portfolio_symbol UNIQUE (portfolio_id, symbol)
);

CREATE TABLE robo_portfolio_profile (
                                          id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          portfolio_id        BIGINT         UNIQUE NOT NULL,
                                          risk_profile        VARCHAR(20)    NOT NULL,
                                          current_value       NUMERIC(19, 4) NOT NULL,
                                          invested_amount     NUMERIC(19, 4) NOT NULL,
                                          status              VARCHAR(1)     NOT NULL,
                                          pnl                 NUMERIC(19, 4),
                                          created_date        TIMESTAMP      NOT NULL
);

CREATE TABLE recommendation (
                                        id                   BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        portfolio_id         BIGINT         NOT NULL,
                                        risk_profile         VARCHAR(20)    NOT NULL,
                                        portfolio_allocation VARCHAR(1000)  NOT NULL,
                                        pnl                 NUMERIC(19, 4),
                                        prompt              TEXT            NOT NULL,
                                        recommendation      TEXT            NOT NULL,
                                        trigger_reason      TEXT            NOT NULL,
                                        status              VARCHAR(1)     NOT NULL,
                                        triggered_at        TIMESTAMP      NOT NULL,
                                        generated_at        TIMESTAMP      NOT NULL
);
CREATE INDEX idx_recommendations_portfolio_id ON recommendation (portfolio_id);